#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTMotor,  HTServo)
#pragma config(Sensor, S4,     sonarSensor,    sensorSONAR)
#pragma config(Motor,  motorA,          gun,           tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  mtr_S1_C1_1,     dualWheels,    tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     motorsRight,   tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C2_1,     motorsLeft,    tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_2,     lift1,         tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_1,     flagMotor,     tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_2,     lift2,				 tmotorTetrix, openLoop)
#pragma config(Servo,  srvo_S1_C4_1,    singleWheelTilt,      tServoContinuousRotation)
#pragma config(Servo,  srvo_S1_C4_2,    rampTilt,             tServoContinuousRotation)
#pragma config(Servo,  srvo_S1_C4_3,    flagExtender,         tServoContinuousRotation)
#pragma config(Servo,  srvo_S1_C4_4,    servoasdf,            tServoNone)
#pragma config(Servo,  srvo_S1_C4_5,    servo6,               tServoNone)
#pragma config(Servo,  srvo_S1_C4_6,    singleWheel,         	tServoContinuousRotation)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
int mode = 1;	//decides whether lift 1 or 2 is being controlled

while(true)
	{

		while(mode == 1)
		{
		nxtDisplayClearTextLine(2);//displays text "lift1" on NXT
		nxtDisplayCenteredTextLine(3, "LIFT_1");

			if(nNxtButtonPressed == 1)
			{
			motor[lift1] = 100;
			}

			else if(nNxtButtonPressed == 2)
			{
			motor[lift1] = -100;
			}

			else
			{
			motor[lift1] = 0;
			}

			if(nNxtButtonPressed == 3)//changes mode to Lift2
			{
			mode = 2;
			wait10Msec(5);
			}
		}

		while(mode == 2)
		{
		nxtDisplayClearTextLine(2);//displays text "lift2" on NXT
		nxtDisplayCenteredTextLine(3, "LIFT_2");

			if(nNxtButtonPressed == 1)
			{
			motor[lift2] = 100;
			}

			else if(nNxtButtonPressed == 2)
			{
			motor[lift2] = -100;
			}
			else
			{
			motor[lift2] = 0;
			}

			if(nNxtButtonPressed == 3)//changes mode to lift1
			{
			mode = 1;
			wait10Msec(5);
			}
		}
	}
}
