#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTMotor,  HTServo)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Motor,  mtr_S1_C1_1,     motorsRight,   tmotorTetrix, PIDControl, encoder)
#pragma config(Motor,  mtr_S1_C1_2,     pulleyMotor,   tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_1,     flagMotor,     tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_2,     hangingMotor,  tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_1,     motorsLeft,    tmotorTetrix, openLoop, reversed, encoder)
#pragma config(Motor,  mtr_S1_C3_2,     harvestMotor,  tmotorTetrix, openLoop)
#pragma config(Servo,  srvo_S1_C4_1,    gun,                  tServoStandard)
#pragma config(Servo,  srvo_S1_C4_2,    flagExtender,         tServoContinuousRotation)
#pragma config(Servo,  srvo_S1_C4_3,    harvestLifter,        tServoContinuousRotation)
#pragma config(Servo,  srvo_S1_C4_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S1_C4_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C4_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
int mode = 1;//int mode controls whether the pulley or the hanging motor is being controlled

while(true)
{

while(mode == 1)//controll over hanging motor
	{
		nxtDisplayClearTextLine(2);//displays text "hangingMotor" on NXT
		nxtDisplayCenteredTextLine(3, "hangingMotor");

	if(nNxtButtonPressed == 1)
		{
		motor[hangingMotor] = 100;
		motor[pulleyMotor] = -90;
		}

	else if(nNxtButtonPressed == 2)
		{
			motor[hangingMotor] = -100;
		}
	else
		{
		motor[hangingMotor] = 0;
		motor[pulleyMotor] = 0;
		}

	if(nNxtButtonPressed == 3)//changes mode to pulley motor
		{
		mode = 2;
		wait10Msec(5);
		}
	}


while(mode == 2)//control over pulley motor
	{
		nxtDisplayClearTextLine(2);//displays text "pulleyMotor" on NXT
		nxtDisplayCenteredTextLine(3, "pulleyMotor");

		if(nNxtButtonPressed == 1)
		{
		motor[pulleyMotor] = 100;
		}
		else if(nNxtButtonPressed == 2)
		{
		motor[pulleyMotor] = -100;
		}
		else
		{
		motor[pulleyMotor] = 0;
		}

		if(nNxtButtonPressed ==3)//changes mode to hanging motor
			{
			mode = 1;
			wait10Msec(3);
			}
	}

}

}
