#pragma config(Hubs,  S2, HTServo,  none,     none,     none)
#pragma config(Servo,  srvo_S2_C1_1,    pushServo,            tServoContinuousRotation)
#pragma config(Servo,  srvo_S2_C1_2,    servo2,               tServoNone)
#pragma config(Servo,  srvo_S2_C1_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S2_C1_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S2_C1_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S2_C1_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	while(true) {
		if(nNxtButtonPressed == 1)
			servo[pushServo]=256;
		else if(nNxtButtonPressed == 2)
			servo[pushServo]=0;
		else
			servo[pushServo]=128;

	}


}
