#pragma config(Hubs,  S1, HTMotor,  HTServo,  none,     none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Motor,  mtr_S1_C1_1,     Right,         tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C1_2,     Left,          tmotorTetrix, openLoop)
#pragma config(Servo,  srvo_S1_C2_1,    Jimi,                 tServoContinuousRotation)
#pragma config(Servo,  srvo_S1_C2_2,    servo2,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "JoystickDriver.c"
task main()
{
	while(true){
		int flag=0;
		getJoystickSettings(joystick); //store controller input in joystick struct (joystick automatically exists, no need to create it)
		int epsilon = 50;
		if(abs(joystick.joy1_y1)>epsilon){
			flag=1;
			motor[Left] = joystick.joy1_y1*(-100.0/128.0);
		}

		if (abs(joystick.joy1_y2) > epsilon){
			flag=1;
			motor[Right] = joystick.joy1_y2 * (-100.0 / 128.0);
		}

		if(joy1Btn(1)==true){
			flag=1;
			motor[Left]= 100;
			motor[Right]= -100;
		}

		if(joy1Btn(2) == true){
			flag=1;
			motor[Left] = 100;
			motor[Right] = 100;
		}

		if(joy1Btn(3) == true){
			flag=1;
			motor[Left] = -100;
			motor[Right] = 100;
		}

		if(joy1Btn(4) == true){
			flag=1;
			motor[Left] = -100;
			motor[Right] = -100;
		}
		if(flag==0){
			motor[Left]=0;
			motor[Right]=0;
		}
	}

}
