#pragma config(Hubs,  S1, HTServo,  HTMotor,  none,     none)
#pragma config(Sensor, S2,     HTIRS2,         sensorI2CCustom)
#pragma config(Motor,  mtr_S1_C2_1,     motorD,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_2,     motorE,        tmotorTetrix, openLoop)
#pragma config(Servo,  srvo_S1_C1_1,    panServo,             tServoStandard)
#pragma config(Servo,  srvo_S1_C1_2,    servo2,               tServoNone)
#pragma config(Servo,  srvo_S1_C1_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S1_C1_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S1_C1_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C1_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/**
 * This program pans the servo with the IR beacon attached until it finds the IR beacon.
 * The cone around the beacon ensures that vision is limited to sector 5, so that's the one we need to check.
 * Once the scanner finds the beacon, it prints out the servo value on screen.
 * By: Noah Moroze
 * Date: 9/17/2013
 */

#include "drivers/hitechnic-irseeker-v2.h"

// main task
task main ()
{
  int sector = 0;
	// the default DSP mode is 1200 Hz.
  tHTIRS2DSPMode _mode = DSP_1200;
    //eraseDisplay();

      // Read the current non modulated signal direction
servo[panServo] = 0;
wait10Msec(100);
  	for(int i=0; i<256; i++) {
  		servo[panServo] = i;
      sector = HTIRS2readACDir(HTIRS2);
      if(sector==5) {
     		nxtDisplayCenteredTextLine(4, "Found at: %d", i);
     		break;
     	}
      nxtDisplayCenteredTextLine(4, "Scanning: %d", sector);
    }
    while(true);

}
