#pragma config(Sensor, S2,     RCOLOR,         sensorCOLORFULL)
#pragma config(Sensor, S3,     LCOLOR,         sensorCOLORFULL)
#pragma config(Motor,  motorB,          LWHEEL,        tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  motorC,          RWHEEL,        tmotorNXT, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	wait1Msec(1000);
	eraseDisplay();

	while(true) {

	  if(SensorValue[RCOLOR] == BLACKCOLOR) {
	  	if(SensorValue[LCOLOR] == BLACKCOLOR) {
	  		nxtDisplayClearTextLine(2);
	  		motor[LWHEEL] = 20;
	  		motor[RWHEEL] = 20;
	  	}
	  	else if(SensorValue[LCOLOR] == WHITECOLOR) {
	  		nxtDisplayClearTextLine(2);
	  		motor[LWHEEL] = 10;
	  		motor[RWHEEL] = 40;
	  	}
	  	else {
	  		nxtDisplayCenteredTextLine(2, "IT'S A TRAP!");
	  		motor[LWHEEL] = 0;
	  		motor[RWHEEL] = 0;
	  	}
	  }
	  else if (SensorValue[RCOLOR] == WHITECOLOR) {
	  	if(SensorValue[LCOLOR] == BLACKCOLOR) {
	  		nxtDisplayClearTextLine(2);
	  		motor[LWHEEL] = 40;
	  		motor[RWHEEL] = 10;
	  	}
	  	else if(SensorValue[LCOLOR] == WHITECOLOR) {
	  		nxtDisplayCenteredTextLine(2, "INTERSECTION!");
	  		motor[LWHEEL] = 20;
	  		motor[RWHEEL] = -20;
	  		wait1Msec(1000);
	  		while(SensorValue[LCOLOR] == BLACKCOLOR) wait1Msec(1); // Do nothing until the robot aligns itself with the line again.
	  	}
	  	else {
	  		nxtDisplayCenteredTextLine(2, "IT'S A TRAP!");
	  		motor[LWHEEL] = 0;
	  		motor[RWHEEL] = 0;
	  	}
	  }

		nxtDisplayCenteredTextLine(3, "Left Sensor: %d", SensorValue[LCOLOR]);
		nxtDisplayCenteredTextLine(4, "Right Sensor: %d", SensorValue[RCOLOR]);
		wait1Msec(10);

	}
}
