#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTMotor,  HTServo)
#pragma config(Sensor, S2,     HTIRS2,         sensorI2CCustom)
#pragma config(Sensor, S3,		 HTSMUX,				 sensorI2CCustom)
#pragma config(Motor,  mtr_S1_C1_1,     motorsRight,   tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C1_2,     pulleyMotor,   tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_1,     flagMotor,     tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_2,     hangingMotor,  tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_1,     motorsLeft,    tmotorTetrix, openLoop, reversed, encoder)
#pragma config(Motor,  mtr_S1_C3_2,     harvestMotor,  tmotorTetrix, openLoop)
#pragma config(Servo,  srvo_S1_C4_1,    gun,                  tServoStandard)
#pragma config(Servo,  srvo_S1_C4_2,    flagExtender,         tServoContinuousRotation)
#pragma config(Servo,  srvo_S1_C4_3,    harvestLifter,        tServoContinuousRotation)
#pragma config(Servo,  srvo_S1_C4_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S1_C4_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C4_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "Autonomous.c"
#include "line_Tracking.h"
#include "drivers/hitechnic-sensormux.h"
#include "drivers/lego-light.h"

const tMUXSensor RLIGHT = msensor_S3_2;
const tMUXSensor LLIGHT = msensor_S3_1;

static int lineSpeed = -30;
static int lineSpeedSlow = -15;
static int turnSpeed = -60;
static int turnSpeedSlow = -45;
static int lightValue = 45;
static int rampValue = 30;

short leftTurn = 50;
short rightTurn = 50;

void driftLeft(int speed) {
	motor[motorsLeft] = 0;
	motor[motorsRight] = speed;
}

void driftRight(int speed) {
	motor[motorsLeft] = speed;
	motor[motorsRight] = 0;
}

void lineFollow() {
	short r, l, lightSpeed1, lightSpeed2; // lightSpeed1 = line speed, lineSpeed2 = turn speed
	lightSpeed1 = lineSpeedSlow;
	lightSpeed2 = turnSpeedSlow;

	while(true) {
		r = LSvalNorm(RLIGHT);
		l = LSvalNorm(LLIGHT);
		if(r < lightValue) {//if right light sensor senses less light than the gray mats
	  	if(l < lightValue) move(lightSpeed1);//if both the sensors sense less light than the gray mats robot moves forward
	  	else driftLeft(lightSpeed2);//if only right light sensor senses less light than the gray mats robot drifts left
	  }
	  else {
	  	if(l < lightValue) driftRight(lightSpeed2);//if left sensor senses less light than the gray mat but not right, robot drifts right
	  	else {
	  		turn(lightSpeed2);
	  		leftTurn = LSvalNorm(LLIGHT);
	  		pause(0.5); // Don't start checking the sensor until the robot moves off of the line.
	  		while(leftTurn < lightValue) leftTurn = LSvalNorm(LLIGHT); // Do nothing until the robot aligns itself with the line again.
	  	}
	  }
	  if(r < rampValue || l < rampValue) {
			lightSpeed1 = lineSpeed;
			lightSpeed2 = turnSpeed;
	  }
	}
}

task main()
{
	LSsetActive(RLIGHT);
	LSsetActive(LLIGHT);
	pause(1);
	leftTurn = LSvalNorm(LLIGHT);
	rightTurn = LSvalNorm(RLIGHT);
	move(lineSpeed);
	while(leftTurn < lightValue && rightTurn < lightValue) {
		leftTurn = LSvalNorm(LLIGHT);
		rightTurn = LSvalNorm(RLIGHT);
	}
	move(0);
	pause(0.5);
	turn(turnSpeed);
	pause(0.5); // Don't start checking the sensor until the robot moves off of the line.
	rightTurn = LSvalNorm(RLIGHT);
	turn(turnSpeed);
	while(rightTurn < lightValue) rightTurn = LSvalNorm(RLIGHT);
	move(0);
	pause(0.5);
	lineFollow();
}
