#pragma config(Hubs,  S1, HTMotor,  none,     none,     none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Motor,  mtr_S1_C1_1,     dumpMotor,     tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     motorE,        tmotorTetrix, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	while(true) {
		if(nNxtButtonPressed == 1)
			motor[dumpMotor]=100;
		else if(nNxtButtonPressed == 2)
			motor[dumpMotor]=-100;
		else
			motor[dumpMotor]=0;

	}
}
