#pragma config(Motor,  motorB,          b,             tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  motorC,          c,             tmotorNXT, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	motor[b] = 100;
	motor[c] = 100;
	wait1Msec(1000);
	motor[b] = -100;
	motor[c] = -100;
	wait1Msec(1000);
}
