#pragma config(Sensor, S1,     sonarSensor,    sensorSONAR)
#pragma config(Sensor, S2,     sonarSensor2,    sensorSONAR)
#pragma config(Motor,  motorA,          SonarMotor,    tmotorNXT, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

//Ultrasonic Sensor Testing

//Excitement. Math stuff. See notebook entry for detailed data collected.
//Soon to be here: An algorithm to map out the surrounding region in 2D.


//lastupdated Clive 1/6/13

void plotPoint(int nx, int ny);
task main()
{
	//Data collection phase
	int values[128];
	eraseDisplay();
	wait10Msec(50);
	nxtSetPixel(50,32);
	nxtSetPixel(51,33);
	nxtSetPixel(51,31);
	nxtSetPixel(49,33);
	nxtSetPixel(49,31);

	int deg,value;

	int speed=20;
	nMotorEncoder[sonarMotor]=0;
	motor[sonarMotor]=speed;

	while(1){
		deg=nMotorEncoder[sonarMotor];
		if(deg>360){motor[sonarMotor]=-speed;eraseDisplay();}
		if(deg<0){motor[sonarMotor]=speed;eraseDisplay();}

		value=((SensorValue[sonarSensor]>200?SensorValue[sonarSensor2]:SensorValue[sonarSensor])+(SensorValue[sonarSensor2]>200?SensorValue[sonarSensor]:SensorValue[sonarSensor2]))/2;
		/*if(value<100&&value>20)*/plotPoint(cosDegrees(deg)*(value), sinDegrees(deg)*(value));


		/*
		for(int i=0;i<128;i++){
			servo[sonarServo]=i*2;
			values[i]=SensorValue[sonarSensor];
			wait1Msec(10);
		}
		for(int i=0;i<128;i++){
			plotPoint(cosDegrees(i*2*180/255)*(values[i]), sinDegrees(i*2*180/255)*(values[i]));
		}


		for(int i=127;i>=0;i--){
			servo[sonarServo]=i*2;
			values[i]=SensorValue[sonarSensor];
			wait1Msec(10);
		}
		for(int i=0;i<128;i++){
			plotPoint(cosDegrees(i*2*180/255)*(values[i]), sinDegrees(i*2*180/255)*(values[i]));
		}*/
	}
}

void plotPoint(int nx, int ny) {
	float x = (float) nx;
	float y = (float) ny;

	float UpperBounds=100;//this much in each direction x+ x- y+ y-

	writeDebugStream("(%d,%d),",(int)x,(int)y);

	x*=100.0/512*(255/UpperBounds);//xresolution
	y*=64.0/512*(255/UpperBounds);//yresolution
	x+=50;//offset center
	y+=32;//offset center

	nxtSetPixel((int)x, (int)y);
}
