#pragma config(Sensor, S1,     sonarSensor,    sensorSONAR)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

//Ultrasonic Sensor Value Dump

task main()
{
	while(1){
		nxtDisplayCenteredBigTextLine(3,"%d inches",SensorValue[sonarSensor]);
		wait10Msec(5);
	}
}
