#pragma config(Hubs,  S1, HTServo,  none,     none,     none)
#pragma config(Sensor, S4,     sonarSensor,    sensorSONAR)
#pragma config(Servo,  srvo_S1_C1_1,    sonarServo,           tServoStandard)
#pragma config(Servo,  srvo_S1_C1_2,    servo2,               tServoNone)
#pragma config(Servo,  srvo_S1_C1_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S1_C1_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S1_C1_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C1_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

//Ultrasonic Sensor Testing

//Excitement. Math stuff. See notebook entry for detailed data collected.
//Soon to be here: An algorithm to map out the surrounding region in 2D.

//lastupdated Clive 11/4/13
void plotPoint(int nx, int ny);
task main()
{
	//Data collection phase
	int values[128];
	servo[sonarServo]=0;
	wait10Msec(50);
	for(int i=0;i<128;i++){
		servo[sonarServo]=i*2;
		values[i]=SensorValue[sonarSensor];
		wait1Msec(15);
	}

	//Data processing phase
	int x[128];
	int y[128];
	eraseDisplay();
	for(int i=0;i<128;i++){
		x[i]=;
		y[i]=;
	}
	for(int i=0;i<128;i++){
		plotPoint(cosDegrees(i*2*180/255)*(values[i]), sinDegrees(i*2*180/255)*(values[i]));
	}
	nxtSetPixel(50,32);
	nxtSetPixel(51,33);
	nxtSetPixel(51,31);
	nxtSetPixel(49,33);
	nxtSetPixel(49,31);
	while(true);
}

void plotPoint(int nx, int ny) {
	float x = (float) nx;
	float y = (float) ny;

	float ZoomIn=1;

	writeDebugStream("(%d,%d),",(int)x,(int)y);

	x*=100.0/512*ZoomIn;//xresolution
	y*=64.0/512*ZoomIn;//yresolution
	x+=50;//offset center
	y+=32;//offset center

	nxtSetPixel((int)x, (int)y);
}
