#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTMotor,  HTServo)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Motor,  motorA,          gun,           tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  mtr_S1_C1_1,     dualWheels,    tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     motorsRight,   tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C2_1,     motorsLeft,    tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_2,     Lift1,         tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_1,     Lift2,         tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_2,     motorI,        tmotorTetrix, openLoop)
#pragma config(Servo,  srvo_S1_C4_1,    ramp,                 tServoStandard)
#pragma config(Servo,  srvo_S1_C4_2,    singleWheel,          tServoContinuousRotation)
#pragma config(Servo,  srvo_S1_C4_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S1_C4_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S1_C4_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C4_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "JoystickDriver.c" //library with joystick controls



//static speed of robot in precision mode
static int TOP_HAT_FWDBACK_SPEED = 20;
static int TOP_HAT_TURN_SPEED = 20;

static float MOTOR_SCALE = 200.0/256.0; //since joystick values range from -128 to 127 and motors from -100 to 100, we need to scale values from the joystick


//This is the task where we define all servo/"arm" movements.
//By separating the arm and drive tasks, it lets us logically separate our code, and run each one in parallel.
//e.g. you can raise your arm while driving at the same time
task arm() {
	//define servo-position related variables here

	while(true){
		getJoystickSettings(joystick); //grab snapshot of controller positions

		if(joy1Btn(6)){					//pressing right and left triggers  of controler1 control the dual wheels and single wheel at full power,
		motor[dualWheels] = -60;//sucking in or shooting out blocks
		servo[singleWheel]  = 30;
		}
		else if(joy1Btn(8)){
		motor[dualWheels] = 0;
		servo[singleWheel] = 127;
		}

		if(joy1Btn(5)){
		motor[dualWheels] = 60;
		servo[singleWheel] = 240;
		}
		else if(joy1Btn(7)){
		motor[dualWheels] = 0;
		servo[singleWheel] = 127;
		}

		if(joy1Btn(4)){					//pressing number buttons activate lifts. 4 and 2 control lift1, while 1 and 3 control lift2.
		motor[Lift1] = 100;
		}
		else if(joy1Btn(2)){
		motor[Lift1] = -100;
		}
		else{
		motor[Lift1] = 0;
		}

		if(joy1Btn(1)){
		motor[Lift2] = 100;
		}
		else if(joy1Btn(3)){
		motor[Lift2] = -100;
		}
		else{
		motor[Lift2] = 0;
		}

		if(joy2Btn(1)){//  gun
		motor[gun] = 100;
		}
		else if(joy2Btn(3)){
		motor[gun] = - 100;
		}
		else{
		motor[gun]  = 0;
		}

		if(joy2Btn(2)){//controls ramp angle
			servo[ramp] = servo[ramp] - 10;
		}
		else if(joy2Btn(4)){
			servo[ramp] = servo[ramp] + 10;
		}

		if(joy2Btn(6)){//right and left triggers on controler2 controls singleWheel and dual wheel with less power,
			motor[dualWheels] = 80;//which suck in or spit out blocks
			servo[singleWheel] = 180;
		}
		else if(joy2Btn(5)){
			motor[dualWheels] = -80;
			servo[singleWheel] = 70;
		}
		else if(joy2Btn(8)){
			motor[dualWheels] = 0;
			servo[singleWheel] = 127;
		}

	}
}

task main() {
	//variables for motor power that we can modify before feeding to motors
	int powerRight = 0;
	int powerLeft = 0;

	writeDebugStreamLine("");
	writeDebugStreamLine("TELEOP");

	// Initialize robot actuators


	// Wait for start of tele-op phase
	waitForStart();
	writeDebugStreamLine("Begin!");

	StartTask(arm); //start running "arm" task in parallel
	ClearTimer(T1);

	while(true) {
		getJoystickSettings(joystick); //grab snapshot of controller positions

		if (joy1Btn(1))
		{
			powerLeft = 0;
			powerRight = 0;

			if (joystick.joy1_TopHat == 0) {  // forward
				powerLeft = TOP_HAT_FWDBACK_SPEED;
				powerRight = TOP_HAT_FWDBACK_SPEED;
			}
			else if (joystick.joy1_TopHat == 4) { // backward
				powerLeft = -1 * TOP_HAT_FWDBACK_SPEED;
				powerRight = -1 * TOP_HAT_FWDBACK_SPEED;
			}
			else if (joystick.joy1_TopHat == 2) { // right
				powerLeft = TOP_HAT_TURN_SPEED;
				powerRight = -1 * TOP_HAT_TURN_SPEED;
			}
			else if (joystick.joy1_TopHat == 6) { // left
				powerLeft = -1 * TOP_HAT_TURN_SPEED;
				powerRight = TOP_HAT_TURN_SPEED;
			}
		}
		else
		{
			//Since joysticks rarely settle to zero, this makes sure each axis is reset to 0 even if it's within 10 from zero
			//Be sure to copy one of these statements for each joystick you use
			if(abs(joystick.joy1_y1) < 10)
				joystick.joy1_y1 = 0;
			if(abs(joystick.joy1_y2) < 10)
				joystick.joy1_y2 = 0;

			powerRight = MOTOR_SCALE*joystick.joy1_y2;
			powerLeft = MOTOR_SCALE*joystick.joy1_y1;
		}

		motor[motorsRight] = powerRight;
		motor[motorsLeft] = powerLeft;
	}
}
