#pragma config(Sensor, S1,     HTSPB,                sensorI2CCustom9V)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*   HiTechnic Experimenter's Kit for the SuperPro

Experiment - 1 Introduction
Read the status of a switch and display the status on an LED

*/

#include "drivers/hitechnic-superpro.h"

task main() {
  int input;

  while(true) {
  	input = HTSPBreadIO(HTSPB, 0x00);
	  nxtDisplayTextLine(3, "CH0: %4d", input);
	  wait1Msec(50);
  }
}
