#pragma config(Hubs,  S1, HTServo,  HTMotor,  none,     none)
#pragma config(Motor,  mtr_S1_C2_1,     motor1,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_2,     motor2,        tmotorTetrix, openLoop)
#pragma config(Servo,  srvo_S1_C1_1,    stdServo1,            tServoStandard)
#pragma config(Servo,  srvo_S1_C1_2,    stdServo2,            tServoStandard)
#pragma config(Servo,  srvo_S1_C1_3,    stdServo3,            tServoStandard)
#pragma config(Servo,  srvo_S1_C1_4,    contServo1,           tServoContinuousRotation)
#pragma config(Servo,  srvo_S1_C1_5,    contServo2,           tServoContinuousRotation)
#pragma config(Servo,  srvo_S1_C1_6,    contServo3,           tServoContinuousRotation)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

void servoTest() {
	int pos = 128;
	while(true) {
		nNxtExitClicks = 2;
		nxtDisplayClearTextLine(2);
		nxtDisplayCenteredTextLine(3, "Servo test");
		if(nNxtButtonPressed == 1)
			pos++;
		else if(nNxtButtonPressed == 2)
			pos--;
		else if(nNxtButtonPressed == 0)  //exit button
			return;

		servo[stdServo1] = pos;
		servo[stdServo2] = pos;
		servo[stdServo3] = pos;
		wait1Msec(5);
	}
}

void contServoTest() {
	nNxtExitClicks = 2;
	nxtDisplayClearTextLine(2);
	while(true) {
		nxtDisplayCenteredTextLine(3, "Motor test");
		if(nNxtButtonPressed == 1) {
			servo[contServo1] = 255;
			servo[contServo2] = 255;
			servo[contServo3] = 255;
		}
		else if(nNxtButtonPressed == 2) {
			servo[contServo1] = 0;
			servo[contServo2] = 0;
			servo[contServo3] = 0;
		}
		else if(nNxtButtonPressed == 0) { //exit button
			return;
		}
		else {
			servo[contServo1] = 128;
			servo[contServo2] = 128;
			servo[contServo3] = 128;
		}
	}
}
void motorTest() {
	nNxtExitClicks = 2;
	nxtDisplayClearTextLine(2);
	while(true) {
		nxtDisplayCenteredTextLine(3, "Motor test");
		if(nNxtButtonPressed == 1) {
			motor[motor1] = 100;
			motor[motor2] = -100;
		}
		else if(nNxtButtonPressed == 2) {
			motor[motor1] = -100;
			motor[motor2] = 100;
		}
		else if(nNxtButtonPressed == 0) { //exit button
			return;
		}
		else {
			motor[motor1] = 0;
			motor[motor2] = 0;
		}
	}
}

task main()
{
	int displayedTest = 0;
	string tests[] = {"motors", "standard servos", "cont. servos"};
	while(true){
		nxtDisplayCenteredTextLine(2, "Test");
		nxtDisplayCenteredTextLine(3, tests[displayedTest]);

		if(nNxtButtonPressed == 1) {
			displayedTest = (displayedTest + 1) % 3;
			wait10Msec(50);
		}
		else if(nNxtButtonPressed == 2) {
			displayedTest = (displayedTest + 2) % 3;
			wait10Msec(50);
		}
		if(nNxtButtonPressed == 3) {
			switch(displayedTest) {
				case 0:
					motorTest();
					break;
				case 1:
					servoTest();
					break;
				case 2:
					contServoTest();
					break;
			}
		}
	}
}
