#pragma config(Sensor, S1,     HTSPB,                sensorI2CCustom9V)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*   HiTechnic Experimenter's Kit for the SuperPro

Experiment - 1 Introduction
Read the status of a switch and display the status on an LED

*/

#include "drivers/hitechnic-superpro.h"

task main() {
  // Set B0 for output
  HTSPBsetupIO(HTSPB, 0x1);
  HTSPBwriteIO(HTSPB, 0x01);
	while(true) {
		  HTSPBwriteIO(HTSPB, 0x01);
	}
}
