#pragma config(Motor,  motorA,          a,             tmotorNXT, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	motor[a] = 100;
	wait1Msec(1000);
	motor[a] = -100;
}
