#pragma config(Sensor, S1,     RGBColor,       sensorCOLORFULL)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	while(1){
		SetSensorType(RGBColor,sensorCOLORRED);
		wait10Msec(100);
		SetSensorType(RGBColor,sensorCOLORGREEN);
		wait10Msec(100);
		SetSensorType(RGBColor,sensorCOLORBLUE);
		wait10Msec(100);
		SetSensorType(RGBColor,sensorCOLORFULL);
		wait10Msec(100);
	}
}
