#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTServo,  none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Sensor, S2,     HTIRS2,         sensorI2CCustom)
#pragma config(Motor,  mtr_S1_C1_1,     motorsRight,   tmotorTetrix, PIDControl, encoder)
#pragma config(Motor,  mtr_S1_C1_2,     flagMotor,     tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_1,     motorsLeft,    tmotorTetrix, PIDControl, reversed, encoder)
#pragma config(Motor,  mtr_S1_C2_2,     harvestMotor,  tmotorTetrix, openLoop)
#pragma config(Servo,  srvo_S1_C3_1,    gun,                  tServoContinuousRotation)
#pragma config(Servo,  srvo_S1_C3_2,    flagExtender,         tServoContinuousRotation)
#pragma config(Servo,  srvo_S1_C3_3,    harvestLifter,        tServoContinuousRotation)
#pragma config(Servo,  srvo_S1_C3_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "AutonomousStandard.h"

task main(){
	initAutonomous();
	/*turtle("fd 21 lch fd 16 lt 90 fd 36");//Because this is certainly better.*/
	moveDistance(20, 21);
	motor[a] = 100;
	pause(1);
	motor[a] = 0;
	moveDistance(20, 16);
	pause(0.2);
	turnDistance(-20, 90);
	pause(0.2);
	moveDistance(20, 36); //gets to center of ramp
}
