#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTMotor,  HTServo)
#pragma config(Sensor, S2,     HTIRS2,         sensorI2CCustom)
#pragma config(Sensor, S3,		 HTSMUX,				 sensorI2CCustom)
#pragma config(Sensor, S4,     sonarSensor,    sensorSONAR)
#pragma config(Motor,  motorA,          gun,           tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  mtr_S1_C1_1,     dualWheels,    tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     motorsRight,   tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C2_1,     motorsLeft,    tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_2,     lift1,         tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_1,     lift2,         tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_2,     flagMotor,     tmotorTetrix, openLoop)
#pragma config(Servo,  srvo_S1_C4_1,    singleWheelTilt,      tServoStandard)
#pragma config(Servo,  srvo_S1_C4_2,    rampTilt,             tServoStandard)
#pragma config(Servo,  srvo_S1_C4_3,    flagExtender,         tServoContinuousRotation)
#pragma config(Servo,  srvo_S1_C4_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S1_C4_5,    singleWheel,          tServoContinuousRotation)
#pragma config(Servo,  srvo_S1_C4_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "JoystickDriver.c"
#include "Autonomous.c"
#include "Logger.c"
#include "line_Tracking.c"
//#include "CollisionDetection.c"
#include "drivers/hitechnic-irseeker-v2.h"
#include "drivers/hitechnic-sensormux.h"
#include "drivers/lego-light.h"

static int motorSpeed = -50;
static int motorSpeedSlow = -25;
static int centerDist = 40;
static int rampDist = 80;

task main() {
	int initDelay = selectDelay();
	bool shouldQueue = selectQueue();
	bool secondLine = selectLine();
	waitForStart();
	//ClearTimer(T2);
	//StartTask(dropHarvester);
	pause(initDelay);
	StartTask(Logger);

	//addToLogWithTime("AutoStart");

	int sector = 0;
	initAutonomous();
	resetEncoders();
	servo[gun] = 255;

	if(shouldQueue) {
		turnDistance(motorSpeed, 45);
		moveDistance(motorSpeedSlow, 30);
		turnDistance(-1*motorSpeed, 55);
	}
	resetEncoders();

	bool scanning = true;
	move(motorSpeedSlow);
	while(sector!= 5 && abs(nMotorEncoder[motorsRight]) < inchesToEncoder(65)) {
		sector = HTIRS2readACDir(HTIRS2);
	}
	/*
	while(scanning) {
		sector = HTIRS2readACDir(HTIRS2);
		if(sector==5)
			move(motorSpeedSlow);
		else
			scanning = false;
	}
	*/
	move(0);

  addToLogWithTime("IR Detected");
	pause(0.1);
	int currentPos = nMotorEncoder[motorsRight];

	if(inchesToEncoder(35) < abs(nMotorEncoder[motorsRight])) {
	  addToLog("IR second half");
		moveDistance(motorSpeedSlow, 8);
	}
	else {
	  addToLog("IR first half");
		moveDistance(motorSpeedSlow, 7);
	}
	pause(0.1);
	move(0);

	servo[gun] = 0;
	pause(0.5);
	servo[gun] = 255;
  addToLogWithTime("Shot gun");
	while(abs(nMotorEncoder[motorsRight] + currentPos) < inchesToEncoder(73)) {
		move(motorSpeed);
  }
  move(0);
	//while(true);
  addToLogWithTime("Past baskets");

	pause(0.1);
	turnDistance(-1 * motorSpeed, 80);
	lightsCameraAction();

	if(secondLine) {
		while(LSvalNorm(RLIGHT)<lightValue){
			move(-50);
		}
		turnDistance(50, 20);
		moveDistance(-50, 10);
	}
	reverseLineUp();
	resetEncoders();
  int prevEncoder = 0;
 	do {
 		prevEncoder = nMotorEncoder[motorsRight];
		move(-50);
		pause(0.1);
		eraseDisplay();
		nxtDisplayTextLine(2, "%d/%d", nMotorEncoder[motorsRight], inchesToEncoder(40));
	}	while(abs(nMotorEncoder[motorsRight])<inchesToEncoder(40) && nMotorEncoder[motorsRight]!=prevEncoder);
	move(0);

	/*
	moveDistance(motorSpeed, 40);
	turnDistance(-1*motorSpeed, 100);
	moveDistance(-100, 40);
	*/
	/*
	resetEncoders();
	move(-100);
	pause(0.5);
	while(!stationary && nMotorEncoder[motorsRight]<inchesToEncoder(40))
		move(-100);
  move(0);
	addToLogWithTime("On ramp");
	*/

	servo[harvestLifter] = 0;
	pause(8);
	servo[harvestLifter] = 127;

	addToLogWithTime("Dropping lifter");
	pause(2);
	stopLogger();
	pause(1);
}
