#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTMotor,  HTServo)
#pragma config(Sensor, S2,     HTIRS2,         sensorI2CCustom)
#pragma config(Sensor, S3,		 HTSMUX,				 sensorI2CCustom)
#pragma config(Sensor, S4,     sonarSensor,    sensorSONAR)
#pragma config(Motor,  motorA,          gun,           tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  mtr_S1_C1_1,     dualWheels,    tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     motorsRight,   tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C2_1,     motorsLeft,    tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_2,     lift1,         tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_1,     lift2,         tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_2,     flagMotor,     tmotorTetrix, openLoop)
#pragma config(Servo,  srvo_S1_C4_1,    singleWheelTilt,      tServoContinuousRotation)
#pragma config(Servo,  srvo_S1_C4_2,    rampTilt,             tServoContinuousRotation)
#pragma config(Servo,  srvo_S1_C4_3,    flagExtender,         tServoContinuousRotation)
#pragma config(Servo,  srvo_S1_C4_4,    singleWheel,               tServoContinuousRotation)
#pragma config(Servo,  srvo_S1_C4_5,    servo6,               tServoNone)
#pragma config(Servo,  srvo_S1_C4_6,    servonone,          	tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "JoystickDriver.c"
#include "Autonomous.c"
#include "line_Tracking.c"
//#include "CollisionDetection.c"
<<<<<<< HEAD
=======
#include "drivers/hitechnic-irseeker-v2.h"
>>>>>>> c6485bd68941d159fc53d9115680c2e6eff93f30

const int motorSpeed = -50;
const int motorSpeedSlow = -25;

task main() {
	int initDelay = selectDelay();
	bool shouldQueue = selectQueue();
	bool secondLine = selectLine();
	waitForStart();
	//ClearTimer(T2);
	//StartTask(dropHarvester);
	pause(initDelay);

	//addToLogWithTime("AutoStart");

	int sector = 0;
	initAutonomous();
	resetEncoders();

	if(shouldQueue) {
		turnDistance(-1 * motorSpeed, 45);
		moveDistance(motorSpeedSlow, 32);
		turnDistance(motorSpeed, 48);
		pause(1);
	}
	resetEncoders();
	pause(0.1);
	move(motorSpeedSlow);
	while(sector!= 5 && abs(nMotorEncoder[motorsRight]) < inchesToEncoder(65)) {
		sector = HTIRS2readACDir(HTIRS2);
	}
	/*
	while(scanning) {
		sector = HTIRS2readACDir(HTIRS2);
		if(sector==5)
			move(motorSpeedSlow);
		else
			scanning = false;
	}
	*/
	move(0);

	int currentPos = nMotorEncoder[motorsRight];

	if(inchesToEncoder(35) < abs(nMotorEncoder[motorsRight])) {
		//moveDistance(motorSpeedSlow, 8);
	}
	else {
		moveDistance(motorSpeedSlow, 5);
	}
	pause(0.1);

	motor[gun] = -100;
	pause(0.1);
	motor[gun] = 0;

	resetEncoders();
	pause(0.5);
	while(abs(nMotorEncoder[motorsRight] + currentPos) < inchesToEncoder(50)) {
		move(motorSpeed);
  }
  move(0);

	pause(0.1);
	turnDistance(motorSpeed, 45);
	moveDistance(motorSpeed, 5);
	turnDistance(motorSpeed, 45);
	moveDistance(motorSpeed, 25);
	if(robotInTheWay()) {
		moveDistance(motorSpeed, 20);
	}
	turnDistance(motorSpeed, 105);
	moveDistance(motorSpeed, 50);
	/*lightsCameraAction();

	if(secondLine) {
		while(LSvalNorm(RLIGHT)<lightValue){
			move(-50);
		}
		turnDistance(50, 20);
		moveDistance(-50, 10);
	}
	reverseLineUp();
	resetEncoders();
  int prevEncoder = 0;
 	do {
 		prevEncoder = nMotorEncoder[motorsRight];
		move(-50);
		pause(0.1);
		eraseDisplay();
		nxtDisplayTextLine(2, "%d/%d", nMotorEncoder[motorsRight], inchesToEncoder(40));
	}	while(abs(nMotorEncoder[motorsRight])<inchesToEncoder(40) && nMotorEncoder[motorsRight]!=prevEncoder);
	move(0);

	/*
	moveDistance(motorSpeed, 40);
	turnDistance(-1*motorSpeed, 100);
	moveDistance(-100, 40);
	*/
	/*
	resetEncoders();
	move(-100);
	pause(0.5);
	while(!stationary && nMotorEncoder[motorsRight]<inchesToEncoder(40))
		move(-100);
  move(0);
	addToLogWithTime("On ramp");
	*/
/*
	servo[harvestLifter] = 0;
	pause(8);
	servo[harvestLifter] = 127;

	addToLogWithTime("Droppsing lifter");
	pause(2);
	stopLogger();
	pause(1);
	*/
}
