#pragma config(Sensor, S1,     eopd,              sensorAnalogActive)
#pragma config(Sensor, S2,     colorSensor,               sensorCOLORFULL)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "drivers/hitechnic-eopd.h"

task main(){
HTEOPDsetLongRange(eopd);
int val,wait;
while(1){
	nxtDisplayCenteredBigTextLine(3,"%d",val=HTEOPDreadProcessed(eopd));
	if(val>50){
		SetSensorType(colorSensor,sensorCOLORBLUE);
		wait10MSec(20);
		SetSensorType(colorSensor,sensorCOLORGREEN);
		wait10MSec(20);
		SetSensorType(colorSensor,sensorCOLORRED);
		wait10MSec(20);
	}
	else if(val>30){
		SetSensorType(colorSensor,sensorCOLORBLUE);
		wait10MSec(10);
	}
	else if(val>20){
		SetSensorType(colorSensor,sensorCOLORGREEN);
		wait10MSec(10);
	}
	else if(val>12){
		SetSensorType(colorSensor,sensorCOLORRED);
		wait10MSec(10);
	}
	else{
		SetSensorType(colorSensor,sensorCOLORNONE);
	}
}
}
