#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTMotor,  HTServo)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Sensor, S2,     HTIRS2,         sensorI2CCustom)
#pragma config(Sensor, S3,     gyro,           sensorAnalogInactive)
#pragma config(Sensor, S4,     sonarSensor,    sensorSONAR)
#pragma config(Motor,  motorA,          gun,           tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  mtr_S1_C1_1,     motorsRight,   tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C1_2,     motorsLeft,    tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_1,     frontLift,     tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_2,     backLift,      tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_1,     flagMotor,     tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_2,     dualWheels,    tmotorTetrix, openLoop)
#pragma config(Servo,  srvo_S1_C4_1,    singleWheel,          tServoContinuousRotation)
#pragma config(Servo,  srvo_S1_C4_2,    rampTilt,             tServoStandard)
#pragma config(Servo,  srvo_S1_C4_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S1_C4_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S1_C4_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C4_6,    flagExtender,         tServoContinuousRotation)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "JoystickDriver.c"
#include "Autonomous.c"

float distance[] = {18.0, 18.0, 18.0, 18.0, 18.0};  // last five distances from the wall
float deltaDistance = 0.0;                          // change in distance over time

float negativeD, neutralD, positiveD;
float negativeDD, neutralDD, positiveDD;

task getDistances()
{
    while (true)
    {
        ClearTimer(T3);
        for (int i = 4; i > 0; i--)
            distance[i] = distance[i - 1];
        distance[0] = CLIVE; // unit are inches and inches per second
        deltaDistance = (distance[0] - distance[4]) * 1000 / (time1[T3] * 5);
    }
}

float bindValue(float value)
{
    if (value > 1)
        return 1.0;
    if (value < 0)
        return 0.0;
    return value;
}

void fuzzify()
{
    float dist = distance[0];
    float dDist = deltaDistance;
    
    negativeD = (18 - dist) / 6;
    negativeD = bindValue(negativeD);
    neutralD = 1 - abs(18 - dist) / 3;
    neutralD = bindValue(neutralD);
    positiveD = (dist - 18) / 6;
    positiveD = bindValue(positiveD);
    
    negativeDD = dDist;
    negativeDD = bindValue(negativeDD);
    neutralDD = 1 - abs(dDist);
    neutralDD = bindValue(neutralDD);
    positiveDD = 1 - dDist;
    positiveDD = bindValue(positiveDD);
}

void applySetsAndDefuzzify()
{
    float numerator = 0.0;
    float denominator = 0.0;
}

task main()
{
    
}
