#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTServo,  none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Sensor, S3,     sonarSensor,    sensorSONAR)
#pragma config(Motor,  mtr_S1_C1_1,     motorD,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     motorE,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_1,     motorsLeft,    tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C2_2,     motorsRight,   tmotorTetrix, openLoop)
#pragma config(Servo,  srvo_S1_C3_1,    servo1,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_2,    servo2,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

float distance = 18;				// last two distances from the wall
float distancePrev = 18;
float deltaDistance = 0.0;	// change in distance over time

float negativeD, neutralD, positiveD;       // membership grades for the three distance fuzzy input sets
float negativeDD, neutralDD, positiveDD;    // membership grades for the three deltaDistance fuzzy input sets

void getDistances()
{
		ClearTimer(T3);
    distancePrev = distance;
    distance = SensorValue[sonarSensor] / 2.54;
    deltaDistance = (distance - distancePrev);
    wait1Msec(1000 - time1[T3]); // units: inches and inches per second
}

float bindValue(float value)
{
    if (value > 1)
        return 1.0;
    if (value < 0)
        return 0.0;
    return value;
}

void fuzzify()
{
    float dist = distance;
    float dDist = deltaDistance;
    nxtDisplayCenteredTextLine(1, " dist: %f", dist);
    nxtDisplayCenteredTextLine(2, "dDist: %f", dDist);

    negativeD = (18 - dist) / 6;
    negativeD = bindValue(negativeD);
    neutralD = 1 - abs(18 - dist) / 3;
    neutralD = bindValue(neutralD);
    positiveD = (dist - 18) / 6;
    positiveD = bindValue(positiveD);

    negativeDD = -0.5 * dDist;
    negativeDD = bindValue(negativeDD);
    neutralDD = 1 - abs(dDist);
    neutralDD = bindValue(neutralDD);
    positiveDD = 0.5 * dDist;
    positiveDD = bindValue(positiveDD);
}

float applySetsAndDefuzzify()
{
    float numerator = negativeD * 1.5 + neutralD + positiveD * 0.5 + negativeDD * 1.5 + neutralDD + positiveDD * 0.5;
    float denominator = negativeD + neutralD + positiveD + negativeDD + neutralDD + positiveDD;
    return numerator / denominator;
}

void runMotors(float turnRatio)
{
    int leftSpeed = (int)(abs(2 - turnRatio) * 40 + 0.5);
    int rightSpeed = (int)(turnRatio * 40 + 0.5);
    nxtDisplayCenteredTextLine(4, " leftSpeed: %d", leftSpeed);
    nxtDisplayCenteredTextLine(5, "rightSpeed: %d", rightSpeed);
    motor[motorsLeft] = leftSpeed;
    motor[motorsRight] = rightSpeed;
}

void fuzzyFollow()
{
    getDistances();
    fuzzify();
    float turnRatio = applySetsAndDefuzzify();
    nxtDisplayCenteredTextLine(3, "turnRatio: %f", turnRatio);
    runMotors(turnRatio);
}

task main()
{
    while (distance < 30 && distancePrev < 30)
    {
        fuzzyFollow();
    }
    motor[motorsLeft] = 0;
    motor[motorsRight] = 0;
}
