#pragma config(Hubs,  S1, HTMotor,  none,     none,     none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Sensor, S3,     sonarSensor,    sensorSONAR)
#pragma config(Motor,  mtr_S1_C1_1,     motorsRight,   tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C1_2,     motorsLeft,    tmotorTetrix, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

float distance = 18;				// last two distances from the wall
float distancePrev = 18;
float deltaDistance = 0.0;	// change in distance over time

float negativeD, neutralD, positiveD;       // membership grades for the three distance fuzzy input sets
float negativeDD, neutralDD, positiveDD;    // membership grades for the three deltaDistance fuzzy input sets

void getDistances()
{
		ClearTimer(T3);
    distancePrev = distance;
    distance = SensorValue[sonarSensor] / 2.54;
    if (abs(distance - distancePrev) > 1)
    		distance = distancePrev;
    deltaDistance = (distance - distancePrev) * 10;
    wait1Msec(100 - time1[T3]); // units: inches and inches per second
}

float bindValue(float value)
{
    if (value > 1)
        return 1.0;
    if (value < 0)
        return 0.0;
    return value;
}

void fuzzify()
{
    float dist = distance;
    float dDist = deltaDistance;
    nxtDisplayCenteredTextLine(1, " dist: %f", dist);
    nxtDisplayCenteredTextLine(2, "dDist: %f", dDist);

    negativeD = (18 - dist) / 3;
    negativeD = bindValue(negativeD);
    neutralD = 1 - abs(18 - dist) / 1.5;
    neutralD = bindValue(neutralD);
    positiveD = (dist - 18) / 3;
    positiveD = bindValue(positiveD);

    negativeDD = -0.5 * dDist;
    negativeDD = bindValue(negativeDD);
    neutralDD = 1 - abs(dDist);
    neutralDD = bindValue(neutralDD);
    positiveDD = 0.5 * dDist;
    positiveDD = bindValue(positiveDD);
}

float applySetsAndDefuzzify()
{
    float numerator = negativeD * 2.1 + neutralD + positiveD * -0.1 + negativeDD * 1.9 + neutralDD + positiveDD * 0.1;
    float denominator = negativeD + neutralD + positiveD + negativeDD + neutralDD + positiveDD;
    return numerator / denominator;
}

void runMotors(float turnRatio)
{
    int leftSpeed = (int)((2 - turnRatio) * 30 + 0.5);
    int rightSpeed = (int)(turnRatio * 30 + 0.5);
    nxtDisplayCenteredTextLine(4, " leftSpeed: %d", leftSpeed);
    nxtDisplayCenteredTextLine(5, "rightSpeed: %d", rightSpeed);
    motor[motorsLeft] = leftSpeed;
    motor[motorsRight] = rightSpeed;
}

void fuzzyFollow()
{
    getDistances();
    fuzzify();
    float turnRatio = applySetsAndDefuzzify();
    nxtDisplayCenteredTextLine(3, "turnRatio: %f", turnRatio);
    runMotors(turnRatio);
}

task main()
{
		ClearTimer(T2);
		motor[motorsLeft] = 20;
		motor[motorsRight] = 20;
		while (SensorValue[sonarSensor] > 150) {};
    while (time1[T2] < 5000)
    {
        fuzzyFollow();
    }
    motor[motorsLeft] = 0;
    motor[motorsRight] = 0;
    wait1Msec(3000);
}
