#pragma config(Sensor, S2,     HTSMUX,         sensorI2CCustom)
#include "drivers/hitechnic-sensormux.h"
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*
 * $Id: hitechnic-irseeker-v2-test1.c 133 2013-03-10 15:15:38Z xander $
 */

/**
 * hitechnic-irseeker-v2.h provides an API for the HiTechnic IR Seeker V2.  This program
 * demonstrates how to use that API.
 *
 * Changelog:
 * - 0.1: Initial release
 * - 0.2: Partial rewrite by Dick Swan, waits a little longer for sensor initialisation<br>
 *        Nicer intro screen<br>
 *        Less screen flickering, only updated if there's been a change in data.
 * - 0.3: More comments
 * - 0.4: Driver renamed to HTIRS2, all functions have been renamed to HRIRS2
 *
 * Credits:
 * - Big thanks to HiTechnic for providing me with the hardware necessary to write and test this.
 *
 * License: You may use this code as you wish, provided you give credit where it's due.
 *
 * THIS CODE WILL ONLY WORK WITH ROBOTC VERSION 3.59 AND HIGHER.

 * Xander Soldaat (xander_at_botbench.com)
 * Dick Swan
 * 06 April 2010
 * version 0.4
 */

#include "drivers/hitechnic-irseeker-v2.h"
const tMUXSensor HTIRS2 = msensor_S2_1;
// main task
task main ()
{
  int sector = 0;
	// the default DSP mode is 1200 Hz.
  tHTIRS2DSPMode _mode = DSP_1200;

  while(true)
  {


    //eraseDisplay();

      // Read the current non modulated signal direction
      sector = HTIRS2readACDir(HTIRS2);
      nxtDisplayCenteredTextLine(4, "%d", sector);
      if(sector==5)
      	nxtDisplayCenteredTextLine(6, "Detected");
      else
      	nxtDisplayCenteredTextLine(6, "Nope");
  }
}
