#pragma config(Sensor, S3,		 HTSMUX,				 sensorI2CCustom)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "drivers/hitechnic-sensormux.h"
#include "drivers/lego-light.h"

const tMUXSensor RLIGHT = msensor_S3_2;
const tMUXSensor LLIGHT = msensor_S3_1;

task main() {
	LSsetActive(RLIGHT);
	LSsetActive(LLIGHT);
	wait1Msec(100);
	while(true) {
		short leftLight = LSvalNorm(LLIGHT);
		short rightLight = LSvalNorm(RLIGHT);
		nxtDisplayCenteredTextLine(3, "llight: %d", leftLight);
		nxtDisplayCenteredTextLine(4, "rlight: %d", rightLight);
	}
}
