#pragma config(Sensor, S3,     HTSMUX,         sensorI2CCustom)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*
 * $Id: lego-light-SMUX-test2.c 133 2013-03-10 15:15:38Z xander $
 */

/*
 * lego-light.h provides an API for the Lego Light Sensor.  This program
 * demonstrates how to use that API to calibrate the sensor connected to a SMUX.
 *
 * Changelog:
 * - 0.1: Initial release
 * - 0.2: More comments
 *
 * License: You may use this code as you wish, provided you give credit where it's due.
 *
 * THIS CODE WILL ONLY WORK WITH ROBOTC VERSION 3.59 AND HIGHER.

 * Xander Soldaat (xander_at_botbench.com)
 * 25 November 2009
 * version 0.2
 */

#include "drivers/hitechnic-sensormux.h"
#include "drivers/lego-light.h"

// The sensor is connected to the first port
// of the SMUX which is connected to the NXT port S1.
// To access that sensor, we must use msensor_S1_1.  If the sensor
// were connected to 3rd port of the SMUX connected to the NXT port S4,
// we would use msensor_S4_3

// Give the sensor a nice easy to use name
const tMUXSensor LLIGHT = msensor_S3_3;
const tMUXSensor RLIGHT = msensor_S3_4;

task main () {
  int raw = 0;
  int nrm = 0;
  // Get control over the buttons
  nNxtButtonTask  = -2;

  // Turn the light on
  LSsetActive(LLIGHT);

  eraseDisplay();
  nxtDisplayTextLine(0, "Left Light Sensor Cal.");
  nxtDisplayTextLine(2, "Left:  set black");
  nxtDisplayTextLine(3, "Right: set white");
  nxtDisplayTextLine(7, "Center: continue");

  bool cont = true;
  while (cont) {
    switch(nNxtButtonPressed) {
    	// if the center button is pressed exit
    	case kEnterButton:
    										cont = false;
    										wait1Msec(1000);
    										break;
      // if the left button is pressed calibrate the black value for the sensor
      case kLeftButton:
                        LScalLow(LLIGHT);
                        PlaySound(soundBeepBeep);
                        while(bSoundActive) EndTimeSlice();
                        break;
      // if the left button is pressed calibrate the white value for the sensor
      case kRightButton:
                        LScalHigh(LLIGHT);
                        PlaySound(soundBeepBeep);
                        while(bSoundActive) EndTimeSlice();
                        break;
    }
    nxtDisplayClearTextLine(5);
    nxtDisplayClearTextLine(6);

    // Read the raw value of the sensor
    raw = LSvalRaw(LLIGHT);

    // Read the normalised value of the sensor
    nrm = LSvalNorm(LLIGHT);

    // Display the raw and normalised values
    nxtDisplayTextLine(5, "R: %4d N: %4d", raw, nrm);

    // Display the values for black and white
    nxtDisplayTextLine(6, "B: %4d W: %4d", lslow[LLIGHT], lshigh[LLIGHT]);
    wait1Msec(50);
  }

  raw = 0;
  nrm = 0;
  // Get control over the buttons
  nNxtButtonTask  = -2;

  // Turn the light on
  LSsetActive(RLIGHT);

  eraseDisplay();
  nxtDisplayTextLine(0, "Right Light Sensor Cal.");
  nxtDisplayTextLine(2, "Left:  set black");
  nxtDisplayTextLine(3, "Right: set white");
  nxtDisplayTextLine(7, "Gray:       quit");

  while (true) {
    switch(nNxtButtonPressed) {
      // if the left button is pressed calibrate the black value for the sensor
      case kLeftButton:
                        LScalLow(RLIGHT);
                        PlaySound(soundBeepBeep);
                        while(bSoundActive) EndTimeSlice();
                        break;
      // if the left button is pressed calibrate the white value for the sensor
      case kRightButton:
                        LScalHigh(RLIGHT);
                        PlaySound(soundBeepBeep);
                        while(bSoundActive) EndTimeSlice();
                        break;
    }
    nxtDisplayClearTextLine(5);
    nxtDisplayClearTextLine(6);

    // Read the raw value of the sensor
    raw = LSvalRaw(RLIGHT);

    // Read the normalised value of the sensor
    nrm = LSvalNorm(RLIGHT);

    // Display the raw and normalised values
    nxtDisplayTextLine(5, "R: %4d N: %4d", raw, nrm);

    // Display the values for black and white
    nxtDisplayTextLine(6, "B: %4d W: %4d", lslow[RLIGHT], lshigh[RLIGHT]);
    wait1Msec(50);
  }
}

/*
 * $Id: lego-light-SMUX-test2.c 133 2013-03-10 15:15:38Z xander $
 */
